### ISSUE TITLE
Add `cert-transfer` (`mutual-tls-interface`) relation

### ISSUE THREAD

**Issue by sed-i** [canonical/self-signed-certificates-operator#21]
It would be handy if we could have charms trust a CA by means of forming a relation.

For example, I don't need traefik to have a CSR signed by this charm (self-signed-certificates-operator), but I do need traefik to trust the CA, so it can load balance https endpoints.

This is needed to fix https://github.com/canonical/traefik-k8s-operator/issues/214.
Specifically, see diagram in https://github.com/canonical/traefik-k8s-operator/issues/214#issuecomment-1660868997.

**Comment by ghislainbourgeois** [comment]
I think a specific relation would be better, because adding it to the `tls-certificates` would complicate things a bit. The library already reacts to `relation-changed`, and we would need to add more conditions to check. It would also not really make sense in the case of some other providers, like the ACME providers, as the CA is not controlled by the provider in that case.

**Comment by ghislainbourgeois** [comment]
I added this to our backlog.

**Comment by gruyaume** [comment]
I understand the requirement and I agree with @ghislainbourgeois 's approach here.

I believe we may want to change the mutual-tls interface name before getting too far implementing anywhere ([ref](https://warthogs.atlassian.net/browse/TELCO-602))
